thermanager: Ignore unused data variables
 * Ignore unused variables required by the APIs

 * src/main.c:64:37:
    error: unused parameter 'data'

 * src/resource.c:575:36:
    error: unused parameter 'data'

Change-Id: I9ad3c25e203ba9df4315d4a650efec5ff513e967