thermanager: Use libandroidicu and do not directly link to libicuuc
This resolves the following compilation error:

  external/icu/android_icu4c/include/uconfig_local.h:26:2: error: "Please use libandroidicu and do not directly link to libicuuc or libicui18n."

It also ensures that the libicuuc which is an APEX library doesn't
end up in the system image. See:

  warning:  APEX libraries found in system image (see comment for check-apex-libs-absence in build/make/core/main.mk for details)
  Offending entries:
  system/lib/libicuuc.so

Change-Id: I2926bca8c11d0e844db025ea8be36e3513b14fda